"""Add brand to goods and company_items

Revision ID: 3dd1fdf2b394
Revises: 068ff5c80fd5
Create Date: 2025-05-06 17:26:27.292013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd1fdf2b394'
down_revision: Union[str, None] = '068ff5c80fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_items', sa.Column('brand', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_competitors_wb_categories_id'), 'competitors_wb_categories', ['id'], unique=False)
    op.add_column('goods', sa.Column('brand', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_goods_wb_goods_id'), 'goods_wb_goods', ['id'], unique=False)
    op.create_index(op.f('ix_search_wb_categories_id'), 'search_wb_categories', ['id'], unique=False)
    op.create_index(op.f('ix_search_wb_competitors_id'), 'search_wb_competitors', ['id'], unique=False)
    op.create_index(op.f('ix_search_words_wb_categories_id'), 'search_words_wb_categories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_words_wb_categories_id'), table_name='search_words_wb_categories')
    op.drop_index(op.f('ix_search_wb_competitors_id'), table_name='search_wb_competitors')
    op.drop_index(op.f('ix_search_wb_categories_id'), table_name='search_wb_categories')
    op.drop_index(op.f('ix_goods_wb_goods_id'), table_name='goods_wb_goods')
    op.drop_column('goods', 'brand')
    op.drop_index(op.f('ix_competitors_wb_categories_id'), table_name='competitors_wb_categories')
    op.drop_column('company_items', 'brand')
    # ### end Alembic commands ###
